version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: studentmanager_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_KEY=base64:l3lVOYiJUG1huB1OQqW+LVbsrOaDtDTPonEKAS3O1Hg=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=student_manager
            - DB_USERNAME=root
            - DB_PASSWORD=
            - BROADCAST_DRIVER=pusher
            - CACHE_DRIVER=file
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=sync
            - SESSION_DRIVER=file
            - SESSION_LIFETIME=120
            - MEMCACHED_HOST=127.0.0.1
            - REDIS_HOST=127.0.0.1
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - MAIL_DRIVER=smtp
            - MAIL_HOST=smtp.gmail.com
            - MAIL_PORT=587
            - MAIL_USERNAME=lequyhieu1024@gmail.com
            - MAIL_PASSWORD=ntifhakeaxsgmnbv
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS=lequyhieu1024@gmail.com
            - MAIL_FROM_NAME=StudentManager
            - QUEUE_CONNECTION=database
            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_BUCKET=
            - AWS_USE_PATH_STYLE_ENDPOINT=false
            - PUSHER_APP_ID=1853478
            - PUSHER_APP_KEY=262985f14ccd522cd2e9
            - PUSHER_APP_SECRET=0e3062aedacfbf989b1c
            - PUSHER_HOST=
            - PUSHER_PORT=443
            - PUSHER_SCHEME=https
            - PUSHER_APP_CLUSTER=ap1
            - VITE_APP_NAME=StudentManager
            - VITE_PUSHER_APP_KEY=262985f14ccd522cd2e9
            - VITE_PUSHER_HOST=
            - VITE_PUSHER_PORT=443
            - VITE_PUSHER_SCHEME=https
            - VITE_PUSHER_APP_CLUSTER=ap1

    db:
        image: mysql:8.0
        container_name: studentmanager_db
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: student_manager
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: studentmanager_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./ssl:/etc/nginx/ssl
            - .:/var/www/html
        depends_on:
            - app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: studentmanager_phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ""
        depends_on:
            - db

volumes:
    db_data:
