version: '3.8'

services:
    student_manager:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: student_manager_app
        working_dir: /var/www/html
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx_log:/var/log/nginx
            - ./docker/php-fpm:/var/log/php-fpm
            - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
        links:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: student_manager_sql
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
